apiVersion: v1
kind: PersistentVolume
metadata:
  name: media-local
spec:
  capacity:
    storage: 500Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  storageClassName: local-media
  local:
    path: /srv/media
  nodeAffinity:
    required:
      nodeSelectorTerms:
        - matchExpressions:
            - key: node-role.beanlab/media
              operator: In
              values:
                - "true"
