apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jellyfin-media
  namespace: default
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: local-media
  volumeName: media-local
  resources:
    requests:
      storage: 500Gi
