apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: handbrake-media
  namespace: default
spec:
  accessModes:
    - ReadWriteMany
  storageClassName: nfs-media
  volumeName: media-nfs
  resources:
    requests:
      storage: 500Gi
