apiVersion: v1
kind: Service
metadata:
  name: makemkv
  namespace: default
spec:
  selector:
    app: makemkv
  ports:
    - name: web-ui
      port: 5800
      targetPort: web-ui
      protocol: TCP
  type: NodePort
