apiVersion: helm.toolkit.fluxcd.io/v2
kind: HelmRelease
metadata:
  name: headlamp
  namespace: headlamp
spec:
  interval: 30m
  chart:
    spec:
      chart: headlamp
      version: "0.40.x"
      sourceRef:
        kind: HelmRepository
        name: headlamp
        namespace: flux-system
  values:
    replicaCount: 1
    sessionTTL: ""
    service:
      type: NodePort
    clusterRoleBinding:
      create: true
      clusterRoleName: cluster-admin
