apiVersion: v1
kind: ConfigMap
metadata:
  name: coredns-lan
  namespace: dns
data:
  Corefile: |
    . {
      auto {
        directory /data/zones db\.(.*) {1}
        reload 10s
      }
      forward . 8.8.8.8 8.8.4.4
      cache 30
      log
      errors
    }
